[package]
name = "ucan_wasm"
readme = "README.md"
keywords = ["auth", "capability", "rpc"]
categories = ["security", "web-programming", "wasm"]
description = "WebAssembly wrapper for ucan_core"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ucan_core = { path = "../ucan_core" }
